name: kriya_test_vikral
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.1
  http: ^0.13.4
  internet_connection_checker: ^0.0.1+3

dev_dependencies:
  build_runner: ^2.1.4
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^0.15.0+1
  mockito: ^5.0.16
  bloc_test: ^8.3.0

flutter:
  uses-material-design: true
